services:
  - type: web
    name: 123fakturera-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://123fakturera-backend.onrender.com
